#! /bin/bash
# This script automatically generates a tar.bz2 tarball.
# Currently, implementation is pretty dumb. Here's what you have to
# remember:
#  - invoke from directory one jump higher than project root
#  - use game's directory name as first (and only) argument
# This is pretty annoying, but works for now. Will probably
# get better in the future.
#
# By default, no info is being displayed to the user.
#
# This is an example invokation. CCF is located in 'closecombatfree' directory.
# $ ./closecombatfree/tools/archiveProject closecombatfree

cd ${1}
LAST_COMMIT=$(git log -1 --pretty --format=format:"%H")
cd ..

CURRENT_DATE=$(date +%Y.%m.%d)

# This does not check for trailing slashes ('/'). It does not, in fact
# check for anything.
# echo tar -cjf "../${1}_${CURRENT_DATE}_${LAST_COMMIT}.tar.bz2" ${1}/
tar -cjf "${1}_${CURRENT_DATE}_${LAST_COMMIT}.tar.bz2" ${1}/